void nube(){
  text("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",-40,-460);
  text("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",45,-450);
  text("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",0,-440);
  text("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",-40,-430);
}
